<?php
$z[0]=Array("global","",153,179);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",223,253);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",290,317);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",643,678);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n        <div class=\"box fl\">\r\n          <div class=\"title\">[field:title/]</div>\r\n          <div class=\"pd nr\">\r\n            <div class=\"pic fl\"><img src='[field:picname/]' border='0' width='120' height='120' alt='[field:title/]'></div>\r\n            <div class=\"txt fr\">[field:info/]...<a href=\"[field:arcurl/]\"><img src=\"/skin/images/kc.jpg\"></a></div>\r\n          </div>\r\n        </div>\r\n        ",1332,1806);
$z[4][4]['typeid']="3";
$z[4][4]['row']="3";
$z[4][4]['titlelen']="50";
$z[4][4]['infolen']="120";
$z[5]=Array("type","\r\n    <h1><a href=\"[field:typelink/]\" class=\"fr\"><img src=\"/skin/images/more.jpg\" ></a>[field:typename/]</h1>\r\n    ",1951,2100);
$z[5][4]['typeid']="1";
$z[6]=Array("arclist","\r\n          <dl>\r\n            <dt><a href=\"[field:arcurl/]\"><img src='[field:picname/]' border='0' width='120' height='120' alt='[field:title/]'></a></dt>\r\n            <dd><a href=\"[field:arcurl/]\">[field:title/]</a></dd>\r\n          </dl>\r\n          ",5194,5506);
$z[6][4]['typeid']="1";
$z[6][4]['row']="4";
$z[6][4]['titlelen']="50";
$z[7]=Array("type","\r\n    <h1><a href=\"[field:typelink/]\" class=\"fr\"><img src=\"/skin/images/more.jpg\"></a>[field:typename/]</h1>\r\n    ",9844,9992);
$z[7][4]['typeid']="5";
$z[8]=Array("arclist","\r\n        <dl>\r\n          <dt><a href=\"[field:arcurl/]\"><img src='[field:picname/]' border='0' width='120' height='120' alt='[field:title/]'></a></dt>\r\n          <dd><a href=\"[field:arcurl/]\">[field:title/]</a></dd>\r\n        </dl>\r\n        ",10073,10375);
$z[8][4]['typeid']="5";
$z[8][4]['row']="5";
$z[8][4]['titlelen']="50";
$z[9]=Array("include","",10581,10618);
$z[9][4]['filename']="footer.htm";

?>